### ISSUE TITLE
Admin Static Media Error 404

### ISSUE THREAD

**Issue by sadawson** [kenjitoyama/gleba#1]
HTML Generated for the login page:

<pre>&lt;link rel="stylesheet" type="text/css" href="http://localhost:8000/static/media/admin/css/base.css" /&gt;
&lt;link rel="stylesheet" type="text/css" href="http://localhost:8000/static/media/admin/css/login.css" /&gt;
&lt;!--[if lte IE 7]&gt;&lt;link rel="stylesheet" type="text/css" href="http://localhost:8000/static/media/admin/css/ie.css" /&gt;&lt;![endif]--&gt;

&lt;script type="text/javascript"&gt;window.__admin_media_prefix__ = "http://localhost:8000/static/media/admin/";&lt;/script&gt;
</pre>

On my install the path on the filesystem to this resource is "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/media/css"

This is dependent on the install. Need to set this path in settings-local.py and setting.py to this location in a way that it will resolve it no matter how Django is installed.

**Comment by sadawson** [comment]
Install instructions state:
<i>Make a symlink to the Django admin files from the glebaAdmin media folder. My Django distribution in Arch Linux is on /usr/lib/python2.7/site-packages/django/contrib/admin/media/, but yours might be in another location.</i>

Is there a more elegant way to resolve and configure this path within the settings?

**Comment by sadawson** [comment]
Django Documenation states:

<blockquote>Note that the Django development server automagically serves the static files of the admin app, but this is not the case when you use any other server arrangement.</blockquote>

<a href="https://docs.djangoproject.com/en/dev/howto/deployment/modwsgi/">https://docs.djangoproject.com/en/dev/howto/deployment/modwsgi/</a>

Why is this not happening in our current deployment when we use <code>./manage runserver --settings=setttings-local</code>?

**Comment by kenjitoyama** [comment]
We had a small bug when we were setting the django admin files to our own. I've used the default now, so it's working with <code>./manage runserver</code>. It's fixed in commit 1c3850a2f74cebc0f4ef61c376bcbdc67532f859.
