### ISSUE TITLE
Incorrect weight recorded after editing variety.

### ISSUE THREAD

**Issue by kenjitoyama** [kenjitoyama/gleba#3]
Let variety A have minimum weight 4.000 and tolerance 0.050, variety B have minimum weight 5.000 and tolerance 0.100.
If the operator records a box with final weight 4.030 of variety A and then edit the history changing the variety to B, then this box will be invalid (i.e. it will be underweight).

We might need to add more checking in the editing otherwise some boxes might have their records corrupted.

**Comment by sadawson** [comment]
Workaround: Delete the box and reweigh it.
